// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: community/v1/community.proto

package communityv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/constell/constell/backend/pkg/proto/community/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CommunityServiceName is the fully-qualified name of the CommunityService service.
	CommunityServiceName = "community.v1.CommunityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CommunityServiceCreateServerProcedure is the fully-qualified name of the CommunityService's
	// CreateServer RPC.
	CommunityServiceCreateServerProcedure = "/community.v1.CommunityService/CreateServer"
	// CommunityServiceGetServerProcedure is the fully-qualified name of the CommunityService's
	// GetServer RPC.
	CommunityServiceGetServerProcedure = "/community.v1.CommunityService/GetServer"
	// CommunityServiceUpdateServerProcedure is the fully-qualified name of the CommunityService's
	// UpdateServer RPC.
	CommunityServiceUpdateServerProcedure = "/community.v1.CommunityService/UpdateServer"
	// CommunityServiceDeleteServerProcedure is the fully-qualified name of the CommunityService's
	// DeleteServer RPC.
	CommunityServiceDeleteServerProcedure = "/community.v1.CommunityService/DeleteServer"
	// CommunityServiceListServersProcedure is the fully-qualified name of the CommunityService's
	// ListServers RPC.
	CommunityServiceListServersProcedure = "/community.v1.CommunityService/ListServers"
	// CommunityServiceCreateChannelProcedure is the fully-qualified name of the CommunityService's
	// CreateChannel RPC.
	CommunityServiceCreateChannelProcedure = "/community.v1.CommunityService/CreateChannel"
	// CommunityServiceGetChannelProcedure is the fully-qualified name of the CommunityService's
	// GetChannel RPC.
	CommunityServiceGetChannelProcedure = "/community.v1.CommunityService/GetChannel"
	// CommunityServiceUpdateChannelProcedure is the fully-qualified name of the CommunityService's
	// UpdateChannel RPC.
	CommunityServiceUpdateChannelProcedure = "/community.v1.CommunityService/UpdateChannel"
	// CommunityServiceDeleteChannelProcedure is the fully-qualified name of the CommunityService's
	// DeleteChannel RPC.
	CommunityServiceDeleteChannelProcedure = "/community.v1.CommunityService/DeleteChannel"
	// CommunityServiceListChannelsProcedure is the fully-qualified name of the CommunityService's
	// ListChannels RPC.
	CommunityServiceListChannelsProcedure = "/community.v1.CommunityService/ListChannels"
	// CommunityServiceJoinServerProcedure is the fully-qualified name of the CommunityService's
	// JoinServer RPC.
	CommunityServiceJoinServerProcedure = "/community.v1.CommunityService/JoinServer"
	// CommunityServiceLeaveServerProcedure is the fully-qualified name of the CommunityService's
	// LeaveServer RPC.
	CommunityServiceLeaveServerProcedure = "/community.v1.CommunityService/LeaveServer"
	// CommunityServiceListMembersProcedure is the fully-qualified name of the CommunityService's
	// ListMembers RPC.
	CommunityServiceListMembersProcedure = "/community.v1.CommunityService/ListMembers"
	// CommunityServiceSendMessageProcedure is the fully-qualified name of the CommunityService's
	// SendMessage RPC.
	CommunityServiceSendMessageProcedure = "/community.v1.CommunityService/SendMessage"
	// CommunityServiceGetMessagesProcedure is the fully-qualified name of the CommunityService's
	// GetMessages RPC.
	CommunityServiceGetMessagesProcedure = "/community.v1.CommunityService/GetMessages"
)

// CommunityServiceClient is a client for the community.v1.CommunityService service.
type CommunityServiceClient interface {
	// --- Server ---
	CreateServer(context.Context, *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error)
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
	UpdateServer(context.Context, *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error)
	DeleteServer(context.Context, *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error)
	ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error)
	// --- Channel ---
	CreateChannel(context.Context, *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error)
	GetChannel(context.Context, *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error)
	UpdateChannel(context.Context, *connect.Request[v1.UpdateChannelRequest]) (*connect.Response[v1.UpdateChannelResponse], error)
	DeleteChannel(context.Context, *connect.Request[v1.DeleteChannelRequest]) (*connect.Response[v1.DeleteChannelResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
	// --- Membership ---
	JoinServer(context.Context, *connect.Request[v1.JoinServerRequest]) (*connect.Response[v1.JoinServerResponse], error)
	LeaveServer(context.Context, *connect.Request[v1.LeaveServerRequest]) (*connect.Response[v1.LeaveServerResponse], error)
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	// --- Channel Messages ---
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	GetMessages(context.Context, *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error)
}

// NewCommunityServiceClient constructs a client for the community.v1.CommunityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCommunityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CommunityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	communityServiceMethods := v1.File_community_v1_community_proto.Services().ByName("CommunityService").Methods()
	return &communityServiceClient{
		createServer: connect.NewClient[v1.CreateServerRequest, v1.CreateServerResponse](
			httpClient,
			baseURL+CommunityServiceCreateServerProcedure,
			connect.WithSchema(communityServiceMethods.ByName("CreateServer")),
			connect.WithClientOptions(opts...),
		),
		getServer: connect.NewClient[v1.GetServerRequest, v1.GetServerResponse](
			httpClient,
			baseURL+CommunityServiceGetServerProcedure,
			connect.WithSchema(communityServiceMethods.ByName("GetServer")),
			connect.WithClientOptions(opts...),
		),
		updateServer: connect.NewClient[v1.UpdateServerRequest, v1.UpdateServerResponse](
			httpClient,
			baseURL+CommunityServiceUpdateServerProcedure,
			connect.WithSchema(communityServiceMethods.ByName("UpdateServer")),
			connect.WithClientOptions(opts...),
		),
		deleteServer: connect.NewClient[v1.DeleteServerRequest, v1.DeleteServerResponse](
			httpClient,
			baseURL+CommunityServiceDeleteServerProcedure,
			connect.WithSchema(communityServiceMethods.ByName("DeleteServer")),
			connect.WithClientOptions(opts...),
		),
		listServers: connect.NewClient[v1.ListServersRequest, v1.ListServersResponse](
			httpClient,
			baseURL+CommunityServiceListServersProcedure,
			connect.WithSchema(communityServiceMethods.ByName("ListServers")),
			connect.WithClientOptions(opts...),
		),
		createChannel: connect.NewClient[v1.CreateChannelRequest, v1.CreateChannelResponse](
			httpClient,
			baseURL+CommunityServiceCreateChannelProcedure,
			connect.WithSchema(communityServiceMethods.ByName("CreateChannel")),
			connect.WithClientOptions(opts...),
		),
		getChannel: connect.NewClient[v1.GetChannelRequest, v1.GetChannelResponse](
			httpClient,
			baseURL+CommunityServiceGetChannelProcedure,
			connect.WithSchema(communityServiceMethods.ByName("GetChannel")),
			connect.WithClientOptions(opts...),
		),
		updateChannel: connect.NewClient[v1.UpdateChannelRequest, v1.UpdateChannelResponse](
			httpClient,
			baseURL+CommunityServiceUpdateChannelProcedure,
			connect.WithSchema(communityServiceMethods.ByName("UpdateChannel")),
			connect.WithClientOptions(opts...),
		),
		deleteChannel: connect.NewClient[v1.DeleteChannelRequest, v1.DeleteChannelResponse](
			httpClient,
			baseURL+CommunityServiceDeleteChannelProcedure,
			connect.WithSchema(communityServiceMethods.ByName("DeleteChannel")),
			connect.WithClientOptions(opts...),
		),
		listChannels: connect.NewClient[v1.ListChannelsRequest, v1.ListChannelsResponse](
			httpClient,
			baseURL+CommunityServiceListChannelsProcedure,
			connect.WithSchema(communityServiceMethods.ByName("ListChannels")),
			connect.WithClientOptions(opts...),
		),
		joinServer: connect.NewClient[v1.JoinServerRequest, v1.JoinServerResponse](
			httpClient,
			baseURL+CommunityServiceJoinServerProcedure,
			connect.WithSchema(communityServiceMethods.ByName("JoinServer")),
			connect.WithClientOptions(opts...),
		),
		leaveServer: connect.NewClient[v1.LeaveServerRequest, v1.LeaveServerResponse](
			httpClient,
			baseURL+CommunityServiceLeaveServerProcedure,
			connect.WithSchema(communityServiceMethods.ByName("LeaveServer")),
			connect.WithClientOptions(opts...),
		),
		listMembers: connect.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+CommunityServiceListMembersProcedure,
			connect.WithSchema(communityServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
		sendMessage: connect.NewClient[v1.SendMessageRequest, v1.SendMessageResponse](
			httpClient,
			baseURL+CommunityServiceSendMessageProcedure,
			connect.WithSchema(communityServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
		getMessages: connect.NewClient[v1.GetMessagesRequest, v1.GetMessagesResponse](
			httpClient,
			baseURL+CommunityServiceGetMessagesProcedure,
			connect.WithSchema(communityServiceMethods.ByName("GetMessages")),
			connect.WithClientOptions(opts...),
		),
	}
}

// communityServiceClient implements CommunityServiceClient.
type communityServiceClient struct {
	createServer  *connect.Client[v1.CreateServerRequest, v1.CreateServerResponse]
	getServer     *connect.Client[v1.GetServerRequest, v1.GetServerResponse]
	updateServer  *connect.Client[v1.UpdateServerRequest, v1.UpdateServerResponse]
	deleteServer  *connect.Client[v1.DeleteServerRequest, v1.DeleteServerResponse]
	listServers   *connect.Client[v1.ListServersRequest, v1.ListServersResponse]
	createChannel *connect.Client[v1.CreateChannelRequest, v1.CreateChannelResponse]
	getChannel    *connect.Client[v1.GetChannelRequest, v1.GetChannelResponse]
	updateChannel *connect.Client[v1.UpdateChannelRequest, v1.UpdateChannelResponse]
	deleteChannel *connect.Client[v1.DeleteChannelRequest, v1.DeleteChannelResponse]
	listChannels  *connect.Client[v1.ListChannelsRequest, v1.ListChannelsResponse]
	joinServer    *connect.Client[v1.JoinServerRequest, v1.JoinServerResponse]
	leaveServer   *connect.Client[v1.LeaveServerRequest, v1.LeaveServerResponse]
	listMembers   *connect.Client[v1.ListMembersRequest, v1.ListMembersResponse]
	sendMessage   *connect.Client[v1.SendMessageRequest, v1.SendMessageResponse]
	getMessages   *connect.Client[v1.GetMessagesRequest, v1.GetMessagesResponse]
}

// CreateServer calls community.v1.CommunityService.CreateServer.
func (c *communityServiceClient) CreateServer(ctx context.Context, req *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error) {
	return c.createServer.CallUnary(ctx, req)
}

// GetServer calls community.v1.CommunityService.GetServer.
func (c *communityServiceClient) GetServer(ctx context.Context, req *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return c.getServer.CallUnary(ctx, req)
}

// UpdateServer calls community.v1.CommunityService.UpdateServer.
func (c *communityServiceClient) UpdateServer(ctx context.Context, req *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error) {
	return c.updateServer.CallUnary(ctx, req)
}

// DeleteServer calls community.v1.CommunityService.DeleteServer.
func (c *communityServiceClient) DeleteServer(ctx context.Context, req *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error) {
	return c.deleteServer.CallUnary(ctx, req)
}

// ListServers calls community.v1.CommunityService.ListServers.
func (c *communityServiceClient) ListServers(ctx context.Context, req *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error) {
	return c.listServers.CallUnary(ctx, req)
}

// CreateChannel calls community.v1.CommunityService.CreateChannel.
func (c *communityServiceClient) CreateChannel(ctx context.Context, req *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error) {
	return c.createChannel.CallUnary(ctx, req)
}

// GetChannel calls community.v1.CommunityService.GetChannel.
func (c *communityServiceClient) GetChannel(ctx context.Context, req *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error) {
	return c.getChannel.CallUnary(ctx, req)
}

// UpdateChannel calls community.v1.CommunityService.UpdateChannel.
func (c *communityServiceClient) UpdateChannel(ctx context.Context, req *connect.Request[v1.UpdateChannelRequest]) (*connect.Response[v1.UpdateChannelResponse], error) {
	return c.updateChannel.CallUnary(ctx, req)
}

// DeleteChannel calls community.v1.CommunityService.DeleteChannel.
func (c *communityServiceClient) DeleteChannel(ctx context.Context, req *connect.Request[v1.DeleteChannelRequest]) (*connect.Response[v1.DeleteChannelResponse], error) {
	return c.deleteChannel.CallUnary(ctx, req)
}

// ListChannels calls community.v1.CommunityService.ListChannels.
func (c *communityServiceClient) ListChannels(ctx context.Context, req *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return c.listChannels.CallUnary(ctx, req)
}

// JoinServer calls community.v1.CommunityService.JoinServer.
func (c *communityServiceClient) JoinServer(ctx context.Context, req *connect.Request[v1.JoinServerRequest]) (*connect.Response[v1.JoinServerResponse], error) {
	return c.joinServer.CallUnary(ctx, req)
}

// LeaveServer calls community.v1.CommunityService.LeaveServer.
func (c *communityServiceClient) LeaveServer(ctx context.Context, req *connect.Request[v1.LeaveServerRequest]) (*connect.Response[v1.LeaveServerResponse], error) {
	return c.leaveServer.CallUnary(ctx, req)
}

// ListMembers calls community.v1.CommunityService.ListMembers.
func (c *communityServiceClient) ListMembers(ctx context.Context, req *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// SendMessage calls community.v1.CommunityService.SendMessage.
func (c *communityServiceClient) SendMessage(ctx context.Context, req *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// GetMessages calls community.v1.CommunityService.GetMessages.
func (c *communityServiceClient) GetMessages(ctx context.Context, req *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error) {
	return c.getMessages.CallUnary(ctx, req)
}

// CommunityServiceHandler is an implementation of the community.v1.CommunityService service.
type CommunityServiceHandler interface {
	// --- Server ---
	CreateServer(context.Context, *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error)
	GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error)
	UpdateServer(context.Context, *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error)
	DeleteServer(context.Context, *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error)
	ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error)
	// --- Channel ---
	CreateChannel(context.Context, *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error)
	GetChannel(context.Context, *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error)
	UpdateChannel(context.Context, *connect.Request[v1.UpdateChannelRequest]) (*connect.Response[v1.UpdateChannelResponse], error)
	DeleteChannel(context.Context, *connect.Request[v1.DeleteChannelRequest]) (*connect.Response[v1.DeleteChannelResponse], error)
	ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error)
	// --- Membership ---
	JoinServer(context.Context, *connect.Request[v1.JoinServerRequest]) (*connect.Response[v1.JoinServerResponse], error)
	LeaveServer(context.Context, *connect.Request[v1.LeaveServerRequest]) (*connect.Response[v1.LeaveServerResponse], error)
	ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error)
	// --- Channel Messages ---
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	GetMessages(context.Context, *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error)
}

// NewCommunityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCommunityServiceHandler(svc CommunityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	communityServiceMethods := v1.File_community_v1_community_proto.Services().ByName("CommunityService").Methods()
	communityServiceCreateServerHandler := connect.NewUnaryHandler(
		CommunityServiceCreateServerProcedure,
		svc.CreateServer,
		connect.WithSchema(communityServiceMethods.ByName("CreateServer")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceGetServerHandler := connect.NewUnaryHandler(
		CommunityServiceGetServerProcedure,
		svc.GetServer,
		connect.WithSchema(communityServiceMethods.ByName("GetServer")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceUpdateServerHandler := connect.NewUnaryHandler(
		CommunityServiceUpdateServerProcedure,
		svc.UpdateServer,
		connect.WithSchema(communityServiceMethods.ByName("UpdateServer")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceDeleteServerHandler := connect.NewUnaryHandler(
		CommunityServiceDeleteServerProcedure,
		svc.DeleteServer,
		connect.WithSchema(communityServiceMethods.ByName("DeleteServer")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceListServersHandler := connect.NewUnaryHandler(
		CommunityServiceListServersProcedure,
		svc.ListServers,
		connect.WithSchema(communityServiceMethods.ByName("ListServers")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceCreateChannelHandler := connect.NewUnaryHandler(
		CommunityServiceCreateChannelProcedure,
		svc.CreateChannel,
		connect.WithSchema(communityServiceMethods.ByName("CreateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceGetChannelHandler := connect.NewUnaryHandler(
		CommunityServiceGetChannelProcedure,
		svc.GetChannel,
		connect.WithSchema(communityServiceMethods.ByName("GetChannel")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceUpdateChannelHandler := connect.NewUnaryHandler(
		CommunityServiceUpdateChannelProcedure,
		svc.UpdateChannel,
		connect.WithSchema(communityServiceMethods.ByName("UpdateChannel")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceDeleteChannelHandler := connect.NewUnaryHandler(
		CommunityServiceDeleteChannelProcedure,
		svc.DeleteChannel,
		connect.WithSchema(communityServiceMethods.ByName("DeleteChannel")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceListChannelsHandler := connect.NewUnaryHandler(
		CommunityServiceListChannelsProcedure,
		svc.ListChannels,
		connect.WithSchema(communityServiceMethods.ByName("ListChannels")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceJoinServerHandler := connect.NewUnaryHandler(
		CommunityServiceJoinServerProcedure,
		svc.JoinServer,
		connect.WithSchema(communityServiceMethods.ByName("JoinServer")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceLeaveServerHandler := connect.NewUnaryHandler(
		CommunityServiceLeaveServerProcedure,
		svc.LeaveServer,
		connect.WithSchema(communityServiceMethods.ByName("LeaveServer")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceListMembersHandler := connect.NewUnaryHandler(
		CommunityServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(communityServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceSendMessageHandler := connect.NewUnaryHandler(
		CommunityServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(communityServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	communityServiceGetMessagesHandler := connect.NewUnaryHandler(
		CommunityServiceGetMessagesProcedure,
		svc.GetMessages,
		connect.WithSchema(communityServiceMethods.ByName("GetMessages")),
		connect.WithHandlerOptions(opts...),
	)
	return "/community.v1.CommunityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CommunityServiceCreateServerProcedure:
			communityServiceCreateServerHandler.ServeHTTP(w, r)
		case CommunityServiceGetServerProcedure:
			communityServiceGetServerHandler.ServeHTTP(w, r)
		case CommunityServiceUpdateServerProcedure:
			communityServiceUpdateServerHandler.ServeHTTP(w, r)
		case CommunityServiceDeleteServerProcedure:
			communityServiceDeleteServerHandler.ServeHTTP(w, r)
		case CommunityServiceListServersProcedure:
			communityServiceListServersHandler.ServeHTTP(w, r)
		case CommunityServiceCreateChannelProcedure:
			communityServiceCreateChannelHandler.ServeHTTP(w, r)
		case CommunityServiceGetChannelProcedure:
			communityServiceGetChannelHandler.ServeHTTP(w, r)
		case CommunityServiceUpdateChannelProcedure:
			communityServiceUpdateChannelHandler.ServeHTTP(w, r)
		case CommunityServiceDeleteChannelProcedure:
			communityServiceDeleteChannelHandler.ServeHTTP(w, r)
		case CommunityServiceListChannelsProcedure:
			communityServiceListChannelsHandler.ServeHTTP(w, r)
		case CommunityServiceJoinServerProcedure:
			communityServiceJoinServerHandler.ServeHTTP(w, r)
		case CommunityServiceLeaveServerProcedure:
			communityServiceLeaveServerHandler.ServeHTTP(w, r)
		case CommunityServiceListMembersProcedure:
			communityServiceListMembersHandler.ServeHTTP(w, r)
		case CommunityServiceSendMessageProcedure:
			communityServiceSendMessageHandler.ServeHTTP(w, r)
		case CommunityServiceGetMessagesProcedure:
			communityServiceGetMessagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCommunityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCommunityServiceHandler struct{}

func (UnimplementedCommunityServiceHandler) CreateServer(context.Context, *connect.Request[v1.CreateServerRequest]) (*connect.Response[v1.CreateServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.CreateServer is not implemented"))
}

func (UnimplementedCommunityServiceHandler) GetServer(context.Context, *connect.Request[v1.GetServerRequest]) (*connect.Response[v1.GetServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.GetServer is not implemented"))
}

func (UnimplementedCommunityServiceHandler) UpdateServer(context.Context, *connect.Request[v1.UpdateServerRequest]) (*connect.Response[v1.UpdateServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.UpdateServer is not implemented"))
}

func (UnimplementedCommunityServiceHandler) DeleteServer(context.Context, *connect.Request[v1.DeleteServerRequest]) (*connect.Response[v1.DeleteServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.DeleteServer is not implemented"))
}

func (UnimplementedCommunityServiceHandler) ListServers(context.Context, *connect.Request[v1.ListServersRequest]) (*connect.Response[v1.ListServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.ListServers is not implemented"))
}

func (UnimplementedCommunityServiceHandler) CreateChannel(context.Context, *connect.Request[v1.CreateChannelRequest]) (*connect.Response[v1.CreateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.CreateChannel is not implemented"))
}

func (UnimplementedCommunityServiceHandler) GetChannel(context.Context, *connect.Request[v1.GetChannelRequest]) (*connect.Response[v1.GetChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.GetChannel is not implemented"))
}

func (UnimplementedCommunityServiceHandler) UpdateChannel(context.Context, *connect.Request[v1.UpdateChannelRequest]) (*connect.Response[v1.UpdateChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.UpdateChannel is not implemented"))
}

func (UnimplementedCommunityServiceHandler) DeleteChannel(context.Context, *connect.Request[v1.DeleteChannelRequest]) (*connect.Response[v1.DeleteChannelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.DeleteChannel is not implemented"))
}

func (UnimplementedCommunityServiceHandler) ListChannels(context.Context, *connect.Request[v1.ListChannelsRequest]) (*connect.Response[v1.ListChannelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.ListChannels is not implemented"))
}

func (UnimplementedCommunityServiceHandler) JoinServer(context.Context, *connect.Request[v1.JoinServerRequest]) (*connect.Response[v1.JoinServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.JoinServer is not implemented"))
}

func (UnimplementedCommunityServiceHandler) LeaveServer(context.Context, *connect.Request[v1.LeaveServerRequest]) (*connect.Response[v1.LeaveServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.LeaveServer is not implemented"))
}

func (UnimplementedCommunityServiceHandler) ListMembers(context.Context, *connect.Request[v1.ListMembersRequest]) (*connect.Response[v1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.ListMembers is not implemented"))
}

func (UnimplementedCommunityServiceHandler) SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.SendMessage is not implemented"))
}

func (UnimplementedCommunityServiceHandler) GetMessages(context.Context, *connect.Request[v1.GetMessagesRequest]) (*connect.Response[v1.GetMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("community.v1.CommunityService.GetMessages is not implemented"))
}
