// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file notify/v1/notify.proto (package notify.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file notify/v1/notify.proto.
 */
export const file_notify_v1_notify: GenFile = /*@__PURE__*/
  fileDesc("ChZub3RpZnkvdjEvbm90aWZ5LnByb3RvEglub3RpZnkudjEiGAoWR2V0VW5yZWFkQ291bnRzUmVxdWVzdCJPChRVbnJlYWRETUNvbnZlcnNhdGlvbhIXCg9jb252ZXJzYXRpb25faWQYASABKAkSDwoHcGVlcl9pZBgCIAEoCRINCgVjb3VudBgDIAEoBSJICg1VbnJlYWRDaGFubmVsEhIKCmNoYW5uZWxfaWQYASABKAkSFAoMY29tbXVuaXR5X2lkGAIgASgJEg0KBWNvdW50GAMgASgFIqkBChdHZXRVbnJlYWRDb3VudHNSZXNwb25zZRIQCghkbV90b3RhbBgBIAEoBRI5ChBkbV9jb252ZXJzYXRpb25zGAIgAygLMh8ubm90aWZ5LnYxLlVucmVhZERNQ29udmVyc2F0aW9uEhUKDWNoYW5uZWxfdG90YWwYAyABKAUSKgoIY2hhbm5lbHMYBCADKAsyGC5ub3RpZnkudjEuVW5yZWFkQ2hhbm5lbCIsChFNYXJrRE1SZWFkUmVxdWVzdBIXCg9jb252ZXJzYXRpb25faWQYASABKAkiFAoSTWFya0RNUmVhZFJlc3BvbnNlIiwKFk1hcmtDaGFubmVsUmVhZFJlcXVlc3QSEgoKY2hhbm5lbF9pZBgBIAEoCSIZChdNYXJrQ2hhbm5lbFJlYWRSZXNwb25zZTKOAgoNTm90aWZ5U2VydmljZRJYCg9HZXRVbnJlYWRDb3VudHMSIS5ub3RpZnkudjEuR2V0VW5yZWFkQ291bnRzUmVxdWVzdBoiLm5vdGlmeS52MS5HZXRVbnJlYWRDb3VudHNSZXNwb25zZRJJCgpNYXJrRE1SZWFkEhwubm90aWZ5LnYxLk1hcmtETVJlYWRSZXF1ZXN0Gh0ubm90aWZ5LnYxLk1hcmtETVJlYWRSZXNwb25zZRJYCg9NYXJrQ2hhbm5lbFJlYWQSIS5ub3RpZnkudjEuTWFya0NoYW5uZWxSZWFkUmVxdWVzdBoiLm5vdGlmeS52MS5NYXJrQ2hhbm5lbFJlYWRSZXNwb25zZUI5WjdnaXRodWIuY29tL2NvbnN0ZWxsL2NvbnN0ZWxsL2JhY2tlbmQvcGtnL3Byb3RvL25vdGlmeXYxYgZwcm90bzM");

/**
 * @generated from message notify.v1.GetUnreadCountsRequest
 */
export type GetUnreadCountsRequest = Message<"notify.v1.GetUnreadCountsRequest"> & {
};

/**
 * Describes the message notify.v1.GetUnreadCountsRequest.
 * Use `create(GetUnreadCountsRequestSchema)` to create a new message.
 */
export const GetUnreadCountsRequestSchema: GenMessage<GetUnreadCountsRequest> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 0);

/**
 * @generated from message notify.v1.UnreadDMConversation
 */
export type UnreadDMConversation = Message<"notify.v1.UnreadDMConversation"> & {
  /**
   * @generated from field: string conversation_id = 1;
   */
  conversationId: string;

  /**
   * @generated from field: string peer_id = 2;
   */
  peerId: string;

  /**
   * @generated from field: int32 count = 3;
   */
  count: number;
};

/**
 * Describes the message notify.v1.UnreadDMConversation.
 * Use `create(UnreadDMConversationSchema)` to create a new message.
 */
export const UnreadDMConversationSchema: GenMessage<UnreadDMConversation> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 1);

/**
 * @generated from message notify.v1.UnreadChannel
 */
export type UnreadChannel = Message<"notify.v1.UnreadChannel"> & {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId: string;

  /**
   * @generated from field: string community_id = 2;
   */
  communityId: string;

  /**
   * @generated from field: int32 count = 3;
   */
  count: number;
};

/**
 * Describes the message notify.v1.UnreadChannel.
 * Use `create(UnreadChannelSchema)` to create a new message.
 */
export const UnreadChannelSchema: GenMessage<UnreadChannel> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 2);

/**
 * @generated from message notify.v1.GetUnreadCountsResponse
 */
export type GetUnreadCountsResponse = Message<"notify.v1.GetUnreadCountsResponse"> & {
  /**
   * @generated from field: int32 dm_total = 1;
   */
  dmTotal: number;

  /**
   * @generated from field: repeated notify.v1.UnreadDMConversation dm_conversations = 2;
   */
  dmConversations: UnreadDMConversation[];

  /**
   * @generated from field: int32 channel_total = 3;
   */
  channelTotal: number;

  /**
   * @generated from field: repeated notify.v1.UnreadChannel channels = 4;
   */
  channels: UnreadChannel[];
};

/**
 * Describes the message notify.v1.GetUnreadCountsResponse.
 * Use `create(GetUnreadCountsResponseSchema)` to create a new message.
 */
export const GetUnreadCountsResponseSchema: GenMessage<GetUnreadCountsResponse> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 3);

/**
 * @generated from message notify.v1.MarkDMReadRequest
 */
export type MarkDMReadRequest = Message<"notify.v1.MarkDMReadRequest"> & {
  /**
   * @generated from field: string conversation_id = 1;
   */
  conversationId: string;
};

/**
 * Describes the message notify.v1.MarkDMReadRequest.
 * Use `create(MarkDMReadRequestSchema)` to create a new message.
 */
export const MarkDMReadRequestSchema: GenMessage<MarkDMReadRequest> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 4);

/**
 * @generated from message notify.v1.MarkDMReadResponse
 */
export type MarkDMReadResponse = Message<"notify.v1.MarkDMReadResponse"> & {
};

/**
 * Describes the message notify.v1.MarkDMReadResponse.
 * Use `create(MarkDMReadResponseSchema)` to create a new message.
 */
export const MarkDMReadResponseSchema: GenMessage<MarkDMReadResponse> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 5);

/**
 * @generated from message notify.v1.MarkChannelReadRequest
 */
export type MarkChannelReadRequest = Message<"notify.v1.MarkChannelReadRequest"> & {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId: string;
};

/**
 * Describes the message notify.v1.MarkChannelReadRequest.
 * Use `create(MarkChannelReadRequestSchema)` to create a new message.
 */
export const MarkChannelReadRequestSchema: GenMessage<MarkChannelReadRequest> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 6);

/**
 * @generated from message notify.v1.MarkChannelReadResponse
 */
export type MarkChannelReadResponse = Message<"notify.v1.MarkChannelReadResponse"> & {
};

/**
 * Describes the message notify.v1.MarkChannelReadResponse.
 * Use `create(MarkChannelReadResponseSchema)` to create a new message.
 */
export const MarkChannelReadResponseSchema: GenMessage<MarkChannelReadResponse> = /*@__PURE__*/
  messageDesc(file_notify_v1_notify, 7);

/**
 * @generated from service notify.v1.NotifyService
 */
export const NotifyService: GenService<{
  /**
   * @generated from rpc notify.v1.NotifyService.GetUnreadCounts
   */
  getUnreadCounts: {
    methodKind: "unary";
    input: typeof GetUnreadCountsRequestSchema;
    output: typeof GetUnreadCountsResponseSchema;
  },
  /**
   * @generated from rpc notify.v1.NotifyService.MarkDMRead
   */
  markDMRead: {
    methodKind: "unary";
    input: typeof MarkDMReadRequestSchema;
    output: typeof MarkDMReadResponseSchema;
  },
  /**
   * @generated from rpc notify.v1.NotifyService.MarkChannelRead
   */
  markChannelRead: {
    methodKind: "unary";
    input: typeof MarkChannelReadRequestSchema;
    output: typeof MarkChannelReadResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_notify_v1_notify, 0);

