// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: community/v1/community.proto

package communityv1

import (
	v1 "github.com/constell/constell/backend/pkg/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED  ChannelType = 0
	ChannelType_CHANNEL_TYPE_TEXT         ChannelType = 1
	ChannelType_CHANNEL_TYPE_ANNOUNCEMENT ChannelType = 2
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TYPE_UNSPECIFIED",
		1: "CHANNEL_TYPE_TEXT",
		2: "CHANNEL_TYPE_ANNOUNCEMENT",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED":  0,
		"CHANNEL_TYPE_TEXT":         1,
		"CHANNEL_TYPE_ANNOUNCEMENT": 2,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_community_v1_community_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_community_v1_community_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{0}
}

type Community struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	OwnerId       string                 `protobuf:"bytes,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_community_v1_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{0}
}

func (x *Community) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Community) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Community) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Community) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Community) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Community) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Community) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityRequest) Reset() {
	*x = CreateCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityRequest) ProtoMessage() {}

func (x *CreateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityRequest.ProtoReflect.Descriptor instead.
func (*CreateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommunityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCommunityRequest) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type CreateCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityResponse) Reset() {
	*x = CreateCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityResponse) ProtoMessage() {}

func (x *CreateCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityResponse.ProtoReflect.Descriptor instead.
func (*CreateCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type GetCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityRequest) Reset() {
	*x = GetCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityRequest) ProtoMessage() {}

func (x *GetCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type GetCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityResponse) Reset() {
	*x = GetCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityResponse) ProtoMessage() {}

func (x *GetCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityResponse.ProtoReflect.Descriptor instead.
func (*GetCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type UpdateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityRequest) Reset() {
	*x = UpdateCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityRequest) ProtoMessage() {}

func (x *UpdateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *UpdateCommunityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCommunityRequest) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type UpdateCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityResponse) Reset() {
	*x = UpdateCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityResponse) ProtoMessage() {}

func (x *UpdateCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type DeleteCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommunityRequest) Reset() {
	*x = DeleteCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommunityRequest) ProtoMessage() {}

func (x *DeleteCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommunityRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type DeleteCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommunityResponse) Reset() {
	*x = DeleteCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommunityResponse) ProtoMessage() {}

func (x *DeleteCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommunityResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{8}
}

type ListCommunitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesRequest) Reset() {
	*x = ListCommunitiesRequest{}
	mi := &file_community_v1_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesRequest) ProtoMessage() {}

func (x *ListCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{9}
}

func (x *ListCommunitiesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesResponse) Reset() {
	*x = ListCommunitiesResponse{}
	mi := &file_community_v1_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesResponse) ProtoMessage() {}

func (x *ListCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{10}
}

func (x *ListCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *ListCommunitiesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommunityId   string                 `protobuf:"bytes,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Type          ChannelType            `protobuf:"varint,5,opt,name=type,proto3,enum=community.v1.ChannelType" json:"type,omitempty"`
	Position      int32                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_community_v1_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{11}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Channel) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *Channel) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Channel) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Channel) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Type          ChannelType            `protobuf:"varint,4,opt,name=type,proto3,enum=community.v1.ChannelType" json:"type,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_community_v1_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{12}
}

func (x *CreateChannelRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateChannelRequest) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *CreateChannelRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_community_v1_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{13}
}

func (x *CreateChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_community_v1_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{14}
}

func (x *GetChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelResponse) Reset() {
	*x = GetChannelResponse{}
	mi := &file_community_v1_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelResponse) ProtoMessage() {}

func (x *GetChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelResponse.ProtoReflect.Descriptor instead.
func (*GetChannelResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{15}
}

func (x *GetChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type UpdateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Type          ChannelType            `protobuf:"varint,4,opt,name=type,proto3,enum=community.v1.ChannelType" json:"type,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset() {
	*x = UpdateChannelRequest{}
	mi := &file_community_v1_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelRequest) ProtoMessage() {}

func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelRequest.ProtoReflect.Descriptor instead.
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UpdateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChannelRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpdateChannelRequest) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

func (x *UpdateChannelRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type UpdateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelResponse) Reset() {
	*x = UpdateChannelResponse{}
	mi := &file_community_v1_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChannelResponse) ProtoMessage() {}

func (x *UpdateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChannelResponse.ProtoReflect.Descriptor instead.
func (*UpdateChannelResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type DeleteChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelRequest) Reset() {
	*x = DeleteChannelRequest{}
	mi := &file_community_v1_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelRequest) ProtoMessage() {}

func (x *DeleteChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type DeleteChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelResponse) Reset() {
	*x = DeleteChannelResponse{}
	mi := &file_community_v1_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelResponse) ProtoMessage() {}

func (x *DeleteChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelResponse.ProtoReflect.Descriptor instead.
func (*DeleteChannelResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{19}
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_community_v1_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{20}
}

func (x *ListChannelsRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *ListChannelsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_community_v1_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{21}
}

func (x *ListChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *ListChannelsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CommunityMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RoleIds       []string               `protobuf:"bytes,4,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityMember) Reset() {
	*x = CommunityMember{}
	mi := &file_community_v1_community_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityMember) ProtoMessage() {}

func (x *CommunityMember) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityMember.ProtoReflect.Descriptor instead.
func (*CommunityMember) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{22}
}

func (x *CommunityMember) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *CommunityMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommunityMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CommunityMember) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CommunityMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type JoinCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityRequest) Reset() {
	*x = JoinCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityRequest) ProtoMessage() {}

func (x *JoinCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityRequest.ProtoReflect.Descriptor instead.
func (*JoinCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{23}
}

func (x *JoinCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type JoinCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *CommunityMember       `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityResponse) Reset() {
	*x = JoinCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityResponse) ProtoMessage() {}

func (x *JoinCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityResponse.ProtoReflect.Descriptor instead.
func (*JoinCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{24}
}

func (x *JoinCommunityResponse) GetMember() *CommunityMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type LeaveCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityRequest) Reset() {
	*x = LeaveCommunityRequest{}
	mi := &file_community_v1_community_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityRequest) ProtoMessage() {}

func (x *LeaveCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityRequest.ProtoReflect.Descriptor instead.
func (*LeaveCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{25}
}

func (x *LeaveCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type LeaveCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityResponse) Reset() {
	*x = LeaveCommunityResponse{}
	mi := &file_community_v1_community_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityResponse) ProtoMessage() {}

func (x *LeaveCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityResponse.ProtoReflect.Descriptor instead.
func (*LeaveCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{26}
}

type KickMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // target user to kick
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberRequest) Reset() {
	*x = KickMemberRequest{}
	mi := &file_community_v1_community_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberRequest) ProtoMessage() {}

func (x *KickMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberRequest.ProtoReflect.Descriptor instead.
func (*KickMemberRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{27}
}

func (x *KickMemberRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *KickMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type KickMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberResponse) Reset() {
	*x = KickMemberResponse{}
	mi := &file_community_v1_community_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberResponse) ProtoMessage() {}

func (x *KickMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberResponse.ProtoReflect.Descriptor instead.
func (*KickMemberResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{28}
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_community_v1_community_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{29}
}

func (x *ListMembersRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *ListMembersRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*CommunityMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_community_v1_community_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{30}
}

func (x *ListMembersResponse) GetMembers() []*CommunityMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ChannelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Attachments   []*v1.Attachment       `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Seq           int64                  `protobuf:"varint,8,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_community_v1_community_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{31}
}

func (x *ChannelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelMessage) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ChannelMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChannelMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChannelMessage) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ChannelMessage) GetAttachments() []*v1.Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ChannelMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileIds       []string               `protobuf:"bytes,3,rep,name=file_ids,json=fileIds,proto3" json:"file_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_community_v1_community_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{32}
}

func (x *SendMessageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetFileIds() []string {
	if x != nil {
		return x.FileIds
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChannelMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_community_v1_community_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{33}
}

func (x *SendMessageResponse) GetMessage() *ChannelMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessagesRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChannelId  string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Pagination *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// If non-zero, return only messages with seq > since_seq, ordered ascending
	// (oldest first) for client backfill. Mutually exclusive with pagination.cursor.
	SinceSeq      int64 `protobuf:"varint,3,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_community_v1_community_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{34}
}

func (x *GetMessagesRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetMessagesRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetMessagesRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChannelMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_community_v1_community_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{35}
}

func (x *GetMessagesResponse) GetMessages() []*ChannelMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_community_v1_community_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_community_v1_community_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{37}
}

type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_community_v1_community_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{38}
}

func (x *EditMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EditMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChannelMessage        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageResponse) Reset() {
	*x = EditMessageResponse{}
	mi := &file_community_v1_community_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageResponse) ProtoMessage() {}

func (x *EditMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageResponse.ProtoReflect.Descriptor instead.
func (*EditMessageResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{39}
}

func (x *EditMessageResponse) GetMessage() *ChannelMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_community_v1_community_proto protoreflect.FileDescriptor

const file_community_v1_community_proto_rawDesc = "" +
	"\n" +
	"\x1ccommunity/v1/community.proto\x12\fcommunity.v1\x1a\x16common/v1/common.proto\"\xc5\x01\n" +
	"\tCommunity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"i\n" +
	"\x16CreateCommunityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\"P\n" +
	"\x17CreateCommunityResponse\x125\n" +
	"\tcommunity\x18\x01 \x01(\v2\x17.community.v1.CommunityR\tcommunity\"8\n" +
	"\x13GetCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"M\n" +
	"\x14GetCommunityResponse\x125\n" +
	"\tcommunity\x18\x01 \x01(\v2\x17.community.v1.CommunityR\tcommunity\"\x8c\x01\n" +
	"\x16UpdateCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\"P\n" +
	"\x17UpdateCommunityResponse\x125\n" +
	"\tcommunity\x18\x01 \x01(\v2\x17.community.v1.CommunityR\tcommunity\";\n" +
	"\x16DeleteCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"\x19\n" +
	"\x17DeleteCommunityResponse\"V\n" +
	"\x16ListCommunitiesRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\"\x93\x01\n" +
	"\x17ListCommunitiesResponse\x129\n" +
	"\vcommunities\x18\x01 \x03(\v2\x17.community.v1.CommunityR\vcommunities\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"\xef\x01\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcommunity_id\x18\x02 \x01(\tR\vcommunityId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.community.v1.ChannelTypeR\x04type\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xae\x01\n" +
	"\x14CreateChannelRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.community.v1.ChannelTypeR\x04type\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\"H\n" +
	"\x15CreateChannelResponse\x12/\n" +
	"\achannel\x18\x01 \x01(\v2\x15.community.v1.ChannelR\achannel\"2\n" +
	"\x11GetChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"E\n" +
	"\x12GetChannelResponse\x12/\n" +
	"\achannel\x18\x01 \x01(\v2\x15.community.v1.ChannelR\achannel\"\xaa\x01\n" +
	"\x14UpdateChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.community.v1.ChannelTypeR\x04type\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\"H\n" +
	"\x15UpdateChannelResponse\x12/\n" +
	"\achannel\x18\x01 \x01(\v2\x15.community.v1.ChannelR\achannel\"5\n" +
	"\x14DeleteChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x17\n" +
	"\x15DeleteChannelResponse\"v\n" +
	"\x13ListChannelsRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\"\x88\x01\n" +
	"\x14ListChannelsResponse\x121\n" +
	"\bchannels\x18\x01 \x03(\v2\x15.community.v1.ChannelR\bchannels\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"\xa1\x01\n" +
	"\x0fCommunityMember\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x19\n" +
	"\brole_ids\x18\x04 \x03(\tR\aroleIds\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\"9\n" +
	"\x14JoinCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"N\n" +
	"\x15JoinCommunityResponse\x125\n" +
	"\x06member\x18\x01 \x01(\v2\x1d.community.v1.CommunityMemberR\x06member\":\n" +
	"\x15LeaveCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"\x18\n" +
	"\x16LeaveCommunityResponse\"O\n" +
	"\x11KickMemberRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x14\n" +
	"\x12KickMemberResponse\"u\n" +
	"\x12ListMembersRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\"\x8d\x01\n" +
	"\x13ListMembersResponse\x127\n" +
	"\amembers\x18\x01 \x03(\v2\x1d.community.v1.CommunityMemberR\amembers\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"\xff\x01\n" +
	"\x0eChannelMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x127\n" +
	"\vattachments\x18\a \x03(\v2\x15.common.v1.AttachmentR\vattachments\x12\x10\n" +
	"\x03seq\x18\b \x01(\x03R\x03seq\"h\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bfile_ids\x18\x03 \x03(\tR\afileIds\"M\n" +
	"\x13SendMessageResponse\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.community.v1.ChannelMessageR\amessage\"\x8e\x01\n" +
	"\x12GetMessagesRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12<\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x1b\n" +
	"\tsince_seq\x18\x03 \x01(\x03R\bsinceSeq\"\x8e\x01\n" +
	"\x13GetMessagesResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.community.v1.ChannelMessageR\bmessages\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.common.v1.PaginationResponseR\n" +
	"pagination\"5\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x17\n" +
	"\x15DeleteMessageResponse\"M\n" +
	"\x12EditMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"M\n" +
	"\x13EditMessageResponse\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.community.v1.ChannelMessageR\amessage*a\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANNEL_TYPE_TEXT\x10\x01\x12\x1d\n" +
	"\x19CHANNEL_TYPE_ANNOUNCEMENT\x10\x022\xd1\f\n" +
	"\x10CommunityService\x12^\n" +
	"\x0fCreateCommunity\x12$.community.v1.CreateCommunityRequest\x1a%.community.v1.CreateCommunityResponse\x12U\n" +
	"\fGetCommunity\x12!.community.v1.GetCommunityRequest\x1a\".community.v1.GetCommunityResponse\x12^\n" +
	"\x0fUpdateCommunity\x12$.community.v1.UpdateCommunityRequest\x1a%.community.v1.UpdateCommunityResponse\x12^\n" +
	"\x0fDeleteCommunity\x12$.community.v1.DeleteCommunityRequest\x1a%.community.v1.DeleteCommunityResponse\x12^\n" +
	"\x0fListCommunities\x12$.community.v1.ListCommunitiesRequest\x1a%.community.v1.ListCommunitiesResponse\x12X\n" +
	"\rCreateChannel\x12\".community.v1.CreateChannelRequest\x1a#.community.v1.CreateChannelResponse\x12O\n" +
	"\n" +
	"GetChannel\x12\x1f.community.v1.GetChannelRequest\x1a .community.v1.GetChannelResponse\x12X\n" +
	"\rUpdateChannel\x12\".community.v1.UpdateChannelRequest\x1a#.community.v1.UpdateChannelResponse\x12X\n" +
	"\rDeleteChannel\x12\".community.v1.DeleteChannelRequest\x1a#.community.v1.DeleteChannelResponse\x12U\n" +
	"\fListChannels\x12!.community.v1.ListChannelsRequest\x1a\".community.v1.ListChannelsResponse\x12X\n" +
	"\rJoinCommunity\x12\".community.v1.JoinCommunityRequest\x1a#.community.v1.JoinCommunityResponse\x12[\n" +
	"\x0eLeaveCommunity\x12#.community.v1.LeaveCommunityRequest\x1a$.community.v1.LeaveCommunityResponse\x12O\n" +
	"\n" +
	"KickMember\x12\x1f.community.v1.KickMemberRequest\x1a .community.v1.KickMemberResponse\x12R\n" +
	"\vListMembers\x12 .community.v1.ListMembersRequest\x1a!.community.v1.ListMembersResponse\x12R\n" +
	"\vSendMessage\x12 .community.v1.SendMessageRequest\x1a!.community.v1.SendMessageResponse\x12R\n" +
	"\vGetMessages\x12 .community.v1.GetMessagesRequest\x1a!.community.v1.GetMessagesResponse\x12X\n" +
	"\rDeleteMessage\x12\".community.v1.DeleteMessageRequest\x1a#.community.v1.DeleteMessageResponse\x12R\n" +
	"\vEditMessage\x12 .community.v1.EditMessageRequest\x1a!.community.v1.EditMessageResponseB\xbc\x01\n" +
	"\x10com.community.v1B\x0eCommunityProtoP\x01ZGgithub.com/constell/constell/backend/pkg/proto/community/v1;communityv1\xa2\x02\x03CXX\xaa\x02\fCommunity.V1\xca\x02\fCommunity\\V1\xe2\x02\x18Community\\V1\\GPBMetadata\xea\x02\rCommunity::V1b\x06proto3"

var (
	file_community_v1_community_proto_rawDescOnce sync.Once
	file_community_v1_community_proto_rawDescData []byte
)

func file_community_v1_community_proto_rawDescGZIP() []byte {
	file_community_v1_community_proto_rawDescOnce.Do(func() {
		file_community_v1_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_v1_community_proto_rawDesc), len(file_community_v1_community_proto_rawDesc)))
	})
	return file_community_v1_community_proto_rawDescData
}

var file_community_v1_community_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_community_v1_community_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_community_v1_community_proto_goTypes = []any{
	(ChannelType)(0),                // 0: community.v1.ChannelType
	(*Community)(nil),               // 1: community.v1.Community
	(*CreateCommunityRequest)(nil),  // 2: community.v1.CreateCommunityRequest
	(*CreateCommunityResponse)(nil), // 3: community.v1.CreateCommunityResponse
	(*GetCommunityRequest)(nil),     // 4: community.v1.GetCommunityRequest
	(*GetCommunityResponse)(nil),    // 5: community.v1.GetCommunityResponse
	(*UpdateCommunityRequest)(nil),  // 6: community.v1.UpdateCommunityRequest
	(*UpdateCommunityResponse)(nil), // 7: community.v1.UpdateCommunityResponse
	(*DeleteCommunityRequest)(nil),  // 8: community.v1.DeleteCommunityRequest
	(*DeleteCommunityResponse)(nil), // 9: community.v1.DeleteCommunityResponse
	(*ListCommunitiesRequest)(nil),  // 10: community.v1.ListCommunitiesRequest
	(*ListCommunitiesResponse)(nil), // 11: community.v1.ListCommunitiesResponse
	(*Channel)(nil),                 // 12: community.v1.Channel
	(*CreateChannelRequest)(nil),    // 13: community.v1.CreateChannelRequest
	(*CreateChannelResponse)(nil),   // 14: community.v1.CreateChannelResponse
	(*GetChannelRequest)(nil),       // 15: community.v1.GetChannelRequest
	(*GetChannelResponse)(nil),      // 16: community.v1.GetChannelResponse
	(*UpdateChannelRequest)(nil),    // 17: community.v1.UpdateChannelRequest
	(*UpdateChannelResponse)(nil),   // 18: community.v1.UpdateChannelResponse
	(*DeleteChannelRequest)(nil),    // 19: community.v1.DeleteChannelRequest
	(*DeleteChannelResponse)(nil),   // 20: community.v1.DeleteChannelResponse
	(*ListChannelsRequest)(nil),     // 21: community.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),    // 22: community.v1.ListChannelsResponse
	(*CommunityMember)(nil),         // 23: community.v1.CommunityMember
	(*JoinCommunityRequest)(nil),    // 24: community.v1.JoinCommunityRequest
	(*JoinCommunityResponse)(nil),   // 25: community.v1.JoinCommunityResponse
	(*LeaveCommunityRequest)(nil),   // 26: community.v1.LeaveCommunityRequest
	(*LeaveCommunityResponse)(nil),  // 27: community.v1.LeaveCommunityResponse
	(*KickMemberRequest)(nil),       // 28: community.v1.KickMemberRequest
	(*KickMemberResponse)(nil),      // 29: community.v1.KickMemberResponse
	(*ListMembersRequest)(nil),      // 30: community.v1.ListMembersRequest
	(*ListMembersResponse)(nil),     // 31: community.v1.ListMembersResponse
	(*ChannelMessage)(nil),          // 32: community.v1.ChannelMessage
	(*SendMessageRequest)(nil),      // 33: community.v1.SendMessageRequest
	(*SendMessageResponse)(nil),     // 34: community.v1.SendMessageResponse
	(*GetMessagesRequest)(nil),      // 35: community.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),     // 36: community.v1.GetMessagesResponse
	(*DeleteMessageRequest)(nil),    // 37: community.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),   // 38: community.v1.DeleteMessageResponse
	(*EditMessageRequest)(nil),      // 39: community.v1.EditMessageRequest
	(*EditMessageResponse)(nil),     // 40: community.v1.EditMessageResponse
	(*v1.PaginationRequest)(nil),    // 41: common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),   // 42: common.v1.PaginationResponse
	(*v1.Attachment)(nil),           // 43: common.v1.Attachment
}
var file_community_v1_community_proto_depIdxs = []int32{
	1,  // 0: community.v1.CreateCommunityResponse.community:type_name -> community.v1.Community
	1,  // 1: community.v1.GetCommunityResponse.community:type_name -> community.v1.Community
	1,  // 2: community.v1.UpdateCommunityResponse.community:type_name -> community.v1.Community
	41, // 3: community.v1.ListCommunitiesRequest.pagination:type_name -> common.v1.PaginationRequest
	1,  // 4: community.v1.ListCommunitiesResponse.communities:type_name -> community.v1.Community
	42, // 5: community.v1.ListCommunitiesResponse.pagination:type_name -> common.v1.PaginationResponse
	0,  // 6: community.v1.Channel.type:type_name -> community.v1.ChannelType
	0,  // 7: community.v1.CreateChannelRequest.type:type_name -> community.v1.ChannelType
	12, // 8: community.v1.CreateChannelResponse.channel:type_name -> community.v1.Channel
	12, // 9: community.v1.GetChannelResponse.channel:type_name -> community.v1.Channel
	0,  // 10: community.v1.UpdateChannelRequest.type:type_name -> community.v1.ChannelType
	12, // 11: community.v1.UpdateChannelResponse.channel:type_name -> community.v1.Channel
	41, // 12: community.v1.ListChannelsRequest.pagination:type_name -> common.v1.PaginationRequest
	12, // 13: community.v1.ListChannelsResponse.channels:type_name -> community.v1.Channel
	42, // 14: community.v1.ListChannelsResponse.pagination:type_name -> common.v1.PaginationResponse
	23, // 15: community.v1.JoinCommunityResponse.member:type_name -> community.v1.CommunityMember
	41, // 16: community.v1.ListMembersRequest.pagination:type_name -> common.v1.PaginationRequest
	23, // 17: community.v1.ListMembersResponse.members:type_name -> community.v1.CommunityMember
	42, // 18: community.v1.ListMembersResponse.pagination:type_name -> common.v1.PaginationResponse
	43, // 19: community.v1.ChannelMessage.attachments:type_name -> common.v1.Attachment
	32, // 20: community.v1.SendMessageResponse.message:type_name -> community.v1.ChannelMessage
	41, // 21: community.v1.GetMessagesRequest.pagination:type_name -> common.v1.PaginationRequest
	32, // 22: community.v1.GetMessagesResponse.messages:type_name -> community.v1.ChannelMessage
	42, // 23: community.v1.GetMessagesResponse.pagination:type_name -> common.v1.PaginationResponse
	32, // 24: community.v1.EditMessageResponse.message:type_name -> community.v1.ChannelMessage
	2,  // 25: community.v1.CommunityService.CreateCommunity:input_type -> community.v1.CreateCommunityRequest
	4,  // 26: community.v1.CommunityService.GetCommunity:input_type -> community.v1.GetCommunityRequest
	6,  // 27: community.v1.CommunityService.UpdateCommunity:input_type -> community.v1.UpdateCommunityRequest
	8,  // 28: community.v1.CommunityService.DeleteCommunity:input_type -> community.v1.DeleteCommunityRequest
	10, // 29: community.v1.CommunityService.ListCommunities:input_type -> community.v1.ListCommunitiesRequest
	13, // 30: community.v1.CommunityService.CreateChannel:input_type -> community.v1.CreateChannelRequest
	15, // 31: community.v1.CommunityService.GetChannel:input_type -> community.v1.GetChannelRequest
	17, // 32: community.v1.CommunityService.UpdateChannel:input_type -> community.v1.UpdateChannelRequest
	19, // 33: community.v1.CommunityService.DeleteChannel:input_type -> community.v1.DeleteChannelRequest
	21, // 34: community.v1.CommunityService.ListChannels:input_type -> community.v1.ListChannelsRequest
	24, // 35: community.v1.CommunityService.JoinCommunity:input_type -> community.v1.JoinCommunityRequest
	26, // 36: community.v1.CommunityService.LeaveCommunity:input_type -> community.v1.LeaveCommunityRequest
	28, // 37: community.v1.CommunityService.KickMember:input_type -> community.v1.KickMemberRequest
	30, // 38: community.v1.CommunityService.ListMembers:input_type -> community.v1.ListMembersRequest
	33, // 39: community.v1.CommunityService.SendMessage:input_type -> community.v1.SendMessageRequest
	35, // 40: community.v1.CommunityService.GetMessages:input_type -> community.v1.GetMessagesRequest
	37, // 41: community.v1.CommunityService.DeleteMessage:input_type -> community.v1.DeleteMessageRequest
	39, // 42: community.v1.CommunityService.EditMessage:input_type -> community.v1.EditMessageRequest
	3,  // 43: community.v1.CommunityService.CreateCommunity:output_type -> community.v1.CreateCommunityResponse
	5,  // 44: community.v1.CommunityService.GetCommunity:output_type -> community.v1.GetCommunityResponse
	7,  // 45: community.v1.CommunityService.UpdateCommunity:output_type -> community.v1.UpdateCommunityResponse
	9,  // 46: community.v1.CommunityService.DeleteCommunity:output_type -> community.v1.DeleteCommunityResponse
	11, // 47: community.v1.CommunityService.ListCommunities:output_type -> community.v1.ListCommunitiesResponse
	14, // 48: community.v1.CommunityService.CreateChannel:output_type -> community.v1.CreateChannelResponse
	16, // 49: community.v1.CommunityService.GetChannel:output_type -> community.v1.GetChannelResponse
	18, // 50: community.v1.CommunityService.UpdateChannel:output_type -> community.v1.UpdateChannelResponse
	20, // 51: community.v1.CommunityService.DeleteChannel:output_type -> community.v1.DeleteChannelResponse
	22, // 52: community.v1.CommunityService.ListChannels:output_type -> community.v1.ListChannelsResponse
	25, // 53: community.v1.CommunityService.JoinCommunity:output_type -> community.v1.JoinCommunityResponse
	27, // 54: community.v1.CommunityService.LeaveCommunity:output_type -> community.v1.LeaveCommunityResponse
	29, // 55: community.v1.CommunityService.KickMember:output_type -> community.v1.KickMemberResponse
	31, // 56: community.v1.CommunityService.ListMembers:output_type -> community.v1.ListMembersResponse
	34, // 57: community.v1.CommunityService.SendMessage:output_type -> community.v1.SendMessageResponse
	36, // 58: community.v1.CommunityService.GetMessages:output_type -> community.v1.GetMessagesResponse
	38, // 59: community.v1.CommunityService.DeleteMessage:output_type -> community.v1.DeleteMessageResponse
	40, // 60: community.v1.CommunityService.EditMessage:output_type -> community.v1.EditMessageResponse
	43, // [43:61] is the sub-list for method output_type
	25, // [25:43] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_community_v1_community_proto_init() }
func file_community_v1_community_proto_init() {
	if File_community_v1_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_v1_community_proto_rawDesc), len(file_community_v1_community_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_v1_community_proto_goTypes,
		DependencyIndexes: file_community_v1_community_proto_depIdxs,
		EnumInfos:         file_community_v1_community_proto_enumTypes,
		MessageInfos:      file_community_v1_community_proto_msgTypes,
	}.Build()
	File_community_v1_community_proto = out.File
	file_community_v1_community_proto_goTypes = nil
	file_community_v1_community_proto_depIdxs = nil
}
