// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notify/v1/notify.proto

package notifyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUnreadCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountsRequest) Reset() {
	*x = GetUnreadCountsRequest{}
	mi := &file_notify_v1_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsRequest) ProtoMessage() {}

func (x *GetUnreadCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsRequest) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

type UnreadDMConversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PeerId         string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Count          int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnreadDMConversation) Reset() {
	*x = UnreadDMConversation{}
	mi := &file_notify_v1_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadDMConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadDMConversation) ProtoMessage() {}

func (x *UnreadDMConversation) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadDMConversation.ProtoReflect.Descriptor instead.
func (*UnreadDMConversation) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *UnreadDMConversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UnreadDMConversation) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *UnreadDMConversation) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UnreadChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CommunityId   string                 `protobuf:"bytes,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadChannel) Reset() {
	*x = UnreadChannel{}
	mi := &file_notify_v1_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadChannel) ProtoMessage() {}

func (x *UnreadChannel) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadChannel.ProtoReflect.Descriptor instead.
func (*UnreadChannel) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{2}
}

func (x *UnreadChannel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UnreadChannel) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *UnreadChannel) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetUnreadCountsResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	DmTotal         int32                   `protobuf:"varint,1,opt,name=dm_total,json=dmTotal,proto3" json:"dm_total,omitempty"`
	DmConversations []*UnreadDMConversation `protobuf:"bytes,2,rep,name=dm_conversations,json=dmConversations,proto3" json:"dm_conversations,omitempty"`
	ChannelTotal    int32                   `protobuf:"varint,3,opt,name=channel_total,json=channelTotal,proto3" json:"channel_total,omitempty"`
	Channels        []*UnreadChannel        `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUnreadCountsResponse) Reset() {
	*x = GetUnreadCountsResponse{}
	mi := &file_notify_v1_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsResponse) ProtoMessage() {}

func (x *GetUnreadCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsResponse) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{3}
}

func (x *GetUnreadCountsResponse) GetDmTotal() int32 {
	if x != nil {
		return x.DmTotal
	}
	return 0
}

func (x *GetUnreadCountsResponse) GetDmConversations() []*UnreadDMConversation {
	if x != nil {
		return x.DmConversations
	}
	return nil
}

func (x *GetUnreadCountsResponse) GetChannelTotal() int32 {
	if x != nil {
		return x.ChannelTotal
	}
	return 0
}

func (x *GetUnreadCountsResponse) GetChannels() []*UnreadChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type MarkDMReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkDMReadRequest) Reset() {
	*x = MarkDMReadRequest{}
	mi := &file_notify_v1_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDMReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDMReadRequest) ProtoMessage() {}

func (x *MarkDMReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDMReadRequest.ProtoReflect.Descriptor instead.
func (*MarkDMReadRequest) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *MarkDMReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type MarkDMReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkDMReadResponse) Reset() {
	*x = MarkDMReadResponse{}
	mi := &file_notify_v1_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkDMReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkDMReadResponse) ProtoMessage() {}

func (x *MarkDMReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkDMReadResponse.ProtoReflect.Descriptor instead.
func (*MarkDMReadResponse) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{5}
}

type MarkChannelReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChannelReadRequest) Reset() {
	*x = MarkChannelReadRequest{}
	mi := &file_notify_v1_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChannelReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChannelReadRequest) ProtoMessage() {}

func (x *MarkChannelReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChannelReadRequest.ProtoReflect.Descriptor instead.
func (*MarkChannelReadRequest) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{6}
}

func (x *MarkChannelReadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type MarkChannelReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChannelReadResponse) Reset() {
	*x = MarkChannelReadResponse{}
	mi := &file_notify_v1_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChannelReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChannelReadResponse) ProtoMessage() {}

func (x *MarkChannelReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChannelReadResponse.ProtoReflect.Descriptor instead.
func (*MarkChannelReadResponse) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{7}
}

var File_notify_v1_notify_proto protoreflect.FileDescriptor

const file_notify_v1_notify_proto_rawDesc = "" +
	"\n" +
	"\x16notify/v1/notify.proto\x12\tnotify.v1\"\x18\n" +
	"\x16GetUnreadCountsRequest\"n\n" +
	"\x14UnreadDMConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"g\n" +
	"\rUnreadChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fcommunity_id\x18\x02 \x01(\tR\vcommunityId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xdb\x01\n" +
	"\x17GetUnreadCountsResponse\x12\x19\n" +
	"\bdm_total\x18\x01 \x01(\x05R\admTotal\x12J\n" +
	"\x10dm_conversations\x18\x02 \x03(\v2\x1f.notify.v1.UnreadDMConversationR\x0fdmConversations\x12#\n" +
	"\rchannel_total\x18\x03 \x01(\x05R\fchannelTotal\x124\n" +
	"\bchannels\x18\x04 \x03(\v2\x18.notify.v1.UnreadChannelR\bchannels\"<\n" +
	"\x11MarkDMReadRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x14\n" +
	"\x12MarkDMReadResponse\"7\n" +
	"\x16MarkChannelReadRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x19\n" +
	"\x17MarkChannelReadResponse2\x8e\x02\n" +
	"\rNotifyService\x12X\n" +
	"\x0fGetUnreadCounts\x12!.notify.v1.GetUnreadCountsRequest\x1a\".notify.v1.GetUnreadCountsResponse\x12I\n" +
	"\n" +
	"MarkDMRead\x12\x1c.notify.v1.MarkDMReadRequest\x1a\x1d.notify.v1.MarkDMReadResponse\x12X\n" +
	"\x0fMarkChannelRead\x12!.notify.v1.MarkChannelReadRequest\x1a\".notify.v1.MarkChannelReadResponseB\xa4\x01\n" +
	"\rcom.notify.v1B\vNotifyProtoP\x01ZAgithub.com/constell/constell/backend/pkg/proto/notify/v1;notifyv1\xa2\x02\x03NXX\xaa\x02\tNotify.V1\xca\x02\tNotify\\V1\xe2\x02\x15Notify\\V1\\GPBMetadata\xea\x02\n" +
	"Notify::V1b\x06proto3"

var (
	file_notify_v1_notify_proto_rawDescOnce sync.Once
	file_notify_v1_notify_proto_rawDescData []byte
)

func file_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_v1_notify_proto_rawDesc), len(file_notify_v1_notify_proto_rawDesc)))
	})
	return file_notify_v1_notify_proto_rawDescData
}

var file_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notify_v1_notify_proto_goTypes = []any{
	(*GetUnreadCountsRequest)(nil),  // 0: notify.v1.GetUnreadCountsRequest
	(*UnreadDMConversation)(nil),    // 1: notify.v1.UnreadDMConversation
	(*UnreadChannel)(nil),           // 2: notify.v1.UnreadChannel
	(*GetUnreadCountsResponse)(nil), // 3: notify.v1.GetUnreadCountsResponse
	(*MarkDMReadRequest)(nil),       // 4: notify.v1.MarkDMReadRequest
	(*MarkDMReadResponse)(nil),      // 5: notify.v1.MarkDMReadResponse
	(*MarkChannelReadRequest)(nil),  // 6: notify.v1.MarkChannelReadRequest
	(*MarkChannelReadResponse)(nil), // 7: notify.v1.MarkChannelReadResponse
}
var file_notify_v1_notify_proto_depIdxs = []int32{
	1, // 0: notify.v1.GetUnreadCountsResponse.dm_conversations:type_name -> notify.v1.UnreadDMConversation
	2, // 1: notify.v1.GetUnreadCountsResponse.channels:type_name -> notify.v1.UnreadChannel
	0, // 2: notify.v1.NotifyService.GetUnreadCounts:input_type -> notify.v1.GetUnreadCountsRequest
	4, // 3: notify.v1.NotifyService.MarkDMRead:input_type -> notify.v1.MarkDMReadRequest
	6, // 4: notify.v1.NotifyService.MarkChannelRead:input_type -> notify.v1.MarkChannelReadRequest
	3, // 5: notify.v1.NotifyService.GetUnreadCounts:output_type -> notify.v1.GetUnreadCountsResponse
	5, // 6: notify.v1.NotifyService.MarkDMRead:output_type -> notify.v1.MarkDMReadResponse
	7, // 7: notify.v1.NotifyService.MarkChannelRead:output_type -> notify.v1.MarkChannelReadResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_notify_v1_notify_proto_init() }
func file_notify_v1_notify_proto_init() {
	if File_notify_v1_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_v1_notify_proto_rawDesc), len(file_notify_v1_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_notify_v1_notify_proto_depIdxs,
		MessageInfos:      file_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_notify_v1_notify_proto = out.File
	file_notify_v1_notify_proto_goTypes = nil
	file_notify_v1_notify_proto_depIdxs = nil
}
