// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file search/v1/search.proto (package search.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file search/v1/search.proto.
 */
export const file_search_v1_search: GenFile = /*@__PURE__*/
  fileDesc("ChZzZWFyY2gvdjEvc2VhcmNoLnByb3RvEglzZWFyY2gudjEiUwoNU2VhcmNoUmVxdWVzdBINCgVxdWVyeRgBIAEoCRIkCgV0eXBlcxgCIAMoDjIVLnNlYXJjaC52MS5TZWFyY2hUeXBlEg0KBWxpbWl0GAMgASgFIsQBCg5TZWFyY2hSZXNwb25zZRIkCgV1c2VycxgBIAMoCzIVLnNlYXJjaC52MS5Vc2VyUmVzdWx0EioKCG1lc3NhZ2VzGAIgAygLMhguc2VhcmNoLnYxLk1lc3NhZ2VSZXN1bHQSLwoLZG1fbWVzc2FnZXMYAyADKAsyGi5zZWFyY2gudjEuRE1NZXNzYWdlUmVzdWx0Ei8KC2NvbW11bml0aWVzGAQgAygLMhouc2VhcmNoLnYxLkNvbW11bml0eVJlc3VsdCJRCgpVc2VyUmVzdWx0EgoKAmlkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJEhIKCmF2YXRhcl91cmwYAyABKAkSEQoJcmVsZXZhbmNlGAQgASgBIpABCg1NZXNzYWdlUmVzdWx0EgoKAmlkGAEgASgJEhIKCmNoYW5uZWxfaWQYAiABKAkSFAoMY29tbXVuaXR5X2lkGAMgASgJEhEKCWF1dGhvcl9pZBgEIAEoCRIPCgdjb250ZW50GAUgASgJEhIKCmNyZWF0ZWRfYXQYBiABKAMSEQoJcmVsZXZhbmNlGAcgASgBIn8KD0RNTWVzc2FnZVJlc3VsdBIKCgJpZBgBIAEoCRIXCg9jb252ZXJzYXRpb25faWQYAiABKAkSDwoHcGVlcl9pZBgDIAEoCRIPCgdjb250ZW50GAQgASgJEhIKCmNyZWF0ZWRfYXQYBSABKAMSEQoJcmVsZXZhbmNlGAYgASgBIosBCg9Db21tdW5pdHlSZXN1bHQSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIQCghpY29uX3VybBgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIUCgxtZW1iZXJfY291bnQYBSABKAMSDgoGam9pbmVkGAYgASgIEhEKCXJlbGV2YW5jZRgHIAEoASqUAQoKU2VhcmNoVHlwZRIbChdTRUFSQ0hfVFlQRV9VTlNQRUNJRklFRBAAEhUKEVNFQVJDSF9UWVBFX1VTRVJTEAESGAoUU0VBUkNIX1RZUEVfTUVTU0FHRVMQAhIbChdTRUFSQ0hfVFlQRV9ETV9NRVNTQUdFUxADEhsKF1NFQVJDSF9UWVBFX0NPTU1VTklUSUVTEAQyTgoNU2VhcmNoU2VydmljZRI9CgZTZWFyY2gSGC5zZWFyY2gudjEuU2VhcmNoUmVxdWVzdBoZLnNlYXJjaC52MS5TZWFyY2hSZXNwb25zZUI5WjdnaXRodWIuY29tL2NvbnN0ZWxsL2NvbnN0ZWxsL2JhY2tlbmQvcGtnL3Byb3RvL3NlYXJjaHYxYgZwcm90bzM");

/**
 * @generated from message search.v1.SearchRequest
 */
export type SearchRequest = Message<"search.v1.SearchRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: repeated search.v1.SearchType types = 2;
   */
  types: SearchType[];

  /**
   * @generated from field: int32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message search.v1.SearchRequest.
 * Use `create(SearchRequestSchema)` to create a new message.
 */
export const SearchRequestSchema: GenMessage<SearchRequest> = /*@__PURE__*/
  messageDesc(file_search_v1_search, 0);

/**
 * @generated from message search.v1.SearchResponse
 */
export type SearchResponse = Message<"search.v1.SearchResponse"> & {
  /**
   * @generated from field: repeated search.v1.UserResult users = 1;
   */
  users: UserResult[];

  /**
   * @generated from field: repeated search.v1.MessageResult messages = 2;
   */
  messages: MessageResult[];

  /**
   * @generated from field: repeated search.v1.DMMessageResult dm_messages = 3;
   */
  dmMessages: DMMessageResult[];

  /**
   * @generated from field: repeated search.v1.CommunityResult communities = 4;
   */
  communities: CommunityResult[];
};

/**
 * Describes the message search.v1.SearchResponse.
 * Use `create(SearchResponseSchema)` to create a new message.
 */
export const SearchResponseSchema: GenMessage<SearchResponse> = /*@__PURE__*/
  messageDesc(file_search_v1_search, 1);

/**
 * @generated from message search.v1.UserResult
 */
export type UserResult = Message<"search.v1.UserResult"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname: string;

  /**
   * @generated from field: string avatar_url = 3;
   */
  avatarUrl: string;

  /**
   * @generated from field: double relevance = 4;
   */
  relevance: number;
};

/**
 * Describes the message search.v1.UserResult.
 * Use `create(UserResultSchema)` to create a new message.
 */
export const UserResultSchema: GenMessage<UserResult> = /*@__PURE__*/
  messageDesc(file_search_v1_search, 2);

/**
 * @generated from message search.v1.MessageResult
 */
export type MessageResult = Message<"search.v1.MessageResult"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string channel_id = 2;
   */
  channelId: string;

  /**
   * @generated from field: string community_id = 3;
   */
  communityId: string;

  /**
   * @generated from field: string author_id = 4;
   */
  authorId: string;

  /**
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * @generated from field: int64 created_at = 6;
   */
  createdAt: bigint;

  /**
   * @generated from field: double relevance = 7;
   */
  relevance: number;
};

/**
 * Describes the message search.v1.MessageResult.
 * Use `create(MessageResultSchema)` to create a new message.
 */
export const MessageResultSchema: GenMessage<MessageResult> = /*@__PURE__*/
  messageDesc(file_search_v1_search, 3);

/**
 * @generated from message search.v1.DMMessageResult
 */
export type DMMessageResult = Message<"search.v1.DMMessageResult"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string conversation_id = 2;
   */
  conversationId: string;

  /**
   * @generated from field: string peer_id = 3;
   */
  peerId: string;

  /**
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;

  /**
   * @generated from field: double relevance = 6;
   */
  relevance: number;
};

/**
 * Describes the message search.v1.DMMessageResult.
 * Use `create(DMMessageResultSchema)` to create a new message.
 */
export const DMMessageResultSchema: GenMessage<DMMessageResult> = /*@__PURE__*/
  messageDesc(file_search_v1_search, 4);

/**
 * @generated from message search.v1.CommunityResult
 */
export type CommunityResult = Message<"search.v1.CommunityResult"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string icon_url = 3;
   */
  iconUrl: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: int64 member_count = 5;
   */
  memberCount: bigint;

  /**
   * @generated from field: bool joined = 6;
   */
  joined: boolean;

  /**
   * @generated from field: double relevance = 7;
   */
  relevance: number;
};

/**
 * Describes the message search.v1.CommunityResult.
 * Use `create(CommunityResultSchema)` to create a new message.
 */
export const CommunityResultSchema: GenMessage<CommunityResult> = /*@__PURE__*/
  messageDesc(file_search_v1_search, 5);

/**
 * @generated from enum search.v1.SearchType
 */
export enum SearchType {
  /**
   * @generated from enum value: SEARCH_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SEARCH_TYPE_USERS = 1;
   */
  USERS = 1,

  /**
   * @generated from enum value: SEARCH_TYPE_MESSAGES = 2;
   */
  MESSAGES = 2,

  /**
   * @generated from enum value: SEARCH_TYPE_DM_MESSAGES = 3;
   */
  DM_MESSAGES = 3,

  /**
   * @generated from enum value: SEARCH_TYPE_COMMUNITIES = 4;
   */
  COMMUNITIES = 4,
}

/**
 * Describes the enum search.v1.SearchType.
 */
export const SearchTypeSchema: GenEnum<SearchType> = /*@__PURE__*/
  enumDesc(file_search_v1_search, 0);

/**
 * @generated from service search.v1.SearchService
 */
export const SearchService: GenService<{
  /**
   * @generated from rpc search.v1.SearchService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof SearchRequestSchema;
    output: typeof SearchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_search_v1_search, 0);

