// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file common/v1/common.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/common.proto.
 */
export const file_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZjb21tb24vdjEvY29tbW9uLnByb3RvEgljb21tb24udjEiPQoJVXNlckJyaWVmEgoKAmlkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJEhIKCmF2YXRhcl91cmwYAyABKAkiQgoRUGFnaW5hdGlvblJlcXVlc3QSDQoFbGltaXQYASABKAUSDgoGb2Zmc2V0GAIgASgFEg4KBmN1cnNvchgDIAEoCSJQChJQYWdpbmF0aW9uUmVzcG9uc2USEAoIaGFzX21vcmUYASABKAgSEwoLbmV4dF9jdXJzb3IYAiABKAkSEwoLdG90YWxfY291bnQYAyABKAUigwEKCkF0dGFjaG1lbnQSCgoCaWQYASABKAkSDwoHZmlsZV9pZBgCIAEoCRIQCghmaWxlbmFtZRgDIAEoCRIUCgxjb250ZW50X3R5cGUYBCABKAkSDAoEc2l6ZRgFIAEoAxILCgN1cmwYBiABKAkSFQoNdGh1bWJuYWlsX3VybBgHIAEoCUI5WjdnaXRodWIuY29tL2NvbnN0ZWxsL2NvbnN0ZWxsL2JhY2tlbmQvcGtnL3Byb3RvL2NvbW1vbnYxYgZwcm90bzM");

/**
 * UserBrief is a lightweight user summary embedded in other messages.
 *
 * @generated from message common.v1.UserBrief
 */
export type UserBrief = Message<"common.v1.UserBrief"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string nickname = 2;
   */
  nickname: string;

  /**
   * @generated from field: string avatar_url = 3;
   */
  avatarUrl: string;
};

/**
 * Describes the message common.v1.UserBrief.
 * Use `create(UserBriefSchema)` to create a new message.
 */
export const UserBriefSchema: GenMessage<UserBrief> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 0);

/**
 * PaginationRequest defines how clients request paginated results.
 * Use either offset-based (limit + offset) or cursor-based (limit + cursor),
 * never both.
 *
 * @generated from message common.v1.PaginationRequest
 */
export type PaginationRequest = Message<"common.v1.PaginationRequest"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * @generated from field: string cursor = 3;
   */
  cursor: string;
};

/**
 * Describes the message common.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 1);

/**
 * PaginationResponse is returned alongside any paginated list.
 *
 * @generated from message common.v1.PaginationResponse
 */
export type PaginationResponse = Message<"common.v1.PaginationResponse"> & {
  /**
   * @generated from field: bool has_more = 1;
   */
  hasMore: boolean;

  /**
   * @generated from field: string next_cursor = 2;
   */
  nextCursor: string;

  /**
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message common.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 2);

/**
 * Attachment represents a file attached to a message.
 *
 * @generated from message common.v1.Attachment
 */
export type Attachment = Message<"common.v1.Attachment"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string file_id = 2;
   */
  fileId: string;

  /**
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * @generated from field: string content_type = 4;
   */
  contentType: string;

  /**
   * @generated from field: int64 size = 5;
   */
  size: bigint;

  /**
   * @generated from field: string url = 6;
   */
  url: string;

  /**
   * @generated from field: string thumbnail_url = 7;
   */
  thumbnailUrl: string;
};

/**
 * Describes the message common.v1.Attachment.
 * Use `create(AttachmentSchema)` to create a new message.
 */
export const AttachmentSchema: GenMessage<Attachment> = /*@__PURE__*/
  messageDesc(file_common_v1_common, 3);

