// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: notify/v1/notify.proto

package notifyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/constell/constell/backend/pkg/proto/notify/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotifyServiceName is the fully-qualified name of the NotifyService service.
	NotifyServiceName = "notify.v1.NotifyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotifyServiceGetUnreadCountsProcedure is the fully-qualified name of the NotifyService's
	// GetUnreadCounts RPC.
	NotifyServiceGetUnreadCountsProcedure = "/notify.v1.NotifyService/GetUnreadCounts"
	// NotifyServiceMarkDMReadProcedure is the fully-qualified name of the NotifyService's MarkDMRead
	// RPC.
	NotifyServiceMarkDMReadProcedure = "/notify.v1.NotifyService/MarkDMRead"
	// NotifyServiceMarkChannelReadProcedure is the fully-qualified name of the NotifyService's
	// MarkChannelRead RPC.
	NotifyServiceMarkChannelReadProcedure = "/notify.v1.NotifyService/MarkChannelRead"
)

// NotifyServiceClient is a client for the notify.v1.NotifyService service.
type NotifyServiceClient interface {
	GetUnreadCounts(context.Context, *connect.Request[v1.GetUnreadCountsRequest]) (*connect.Response[v1.GetUnreadCountsResponse], error)
	MarkDMRead(context.Context, *connect.Request[v1.MarkDMReadRequest]) (*connect.Response[v1.MarkDMReadResponse], error)
	MarkChannelRead(context.Context, *connect.Request[v1.MarkChannelReadRequest]) (*connect.Response[v1.MarkChannelReadResponse], error)
}

// NewNotifyServiceClient constructs a client for the notify.v1.NotifyService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotifyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotifyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notifyServiceMethods := v1.File_notify_v1_notify_proto.Services().ByName("NotifyService").Methods()
	return &notifyServiceClient{
		getUnreadCounts: connect.NewClient[v1.GetUnreadCountsRequest, v1.GetUnreadCountsResponse](
			httpClient,
			baseURL+NotifyServiceGetUnreadCountsProcedure,
			connect.WithSchema(notifyServiceMethods.ByName("GetUnreadCounts")),
			connect.WithClientOptions(opts...),
		),
		markDMRead: connect.NewClient[v1.MarkDMReadRequest, v1.MarkDMReadResponse](
			httpClient,
			baseURL+NotifyServiceMarkDMReadProcedure,
			connect.WithSchema(notifyServiceMethods.ByName("MarkDMRead")),
			connect.WithClientOptions(opts...),
		),
		markChannelRead: connect.NewClient[v1.MarkChannelReadRequest, v1.MarkChannelReadResponse](
			httpClient,
			baseURL+NotifyServiceMarkChannelReadProcedure,
			connect.WithSchema(notifyServiceMethods.ByName("MarkChannelRead")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notifyServiceClient implements NotifyServiceClient.
type notifyServiceClient struct {
	getUnreadCounts *connect.Client[v1.GetUnreadCountsRequest, v1.GetUnreadCountsResponse]
	markDMRead      *connect.Client[v1.MarkDMReadRequest, v1.MarkDMReadResponse]
	markChannelRead *connect.Client[v1.MarkChannelReadRequest, v1.MarkChannelReadResponse]
}

// GetUnreadCounts calls notify.v1.NotifyService.GetUnreadCounts.
func (c *notifyServiceClient) GetUnreadCounts(ctx context.Context, req *connect.Request[v1.GetUnreadCountsRequest]) (*connect.Response[v1.GetUnreadCountsResponse], error) {
	return c.getUnreadCounts.CallUnary(ctx, req)
}

// MarkDMRead calls notify.v1.NotifyService.MarkDMRead.
func (c *notifyServiceClient) MarkDMRead(ctx context.Context, req *connect.Request[v1.MarkDMReadRequest]) (*connect.Response[v1.MarkDMReadResponse], error) {
	return c.markDMRead.CallUnary(ctx, req)
}

// MarkChannelRead calls notify.v1.NotifyService.MarkChannelRead.
func (c *notifyServiceClient) MarkChannelRead(ctx context.Context, req *connect.Request[v1.MarkChannelReadRequest]) (*connect.Response[v1.MarkChannelReadResponse], error) {
	return c.markChannelRead.CallUnary(ctx, req)
}

// NotifyServiceHandler is an implementation of the notify.v1.NotifyService service.
type NotifyServiceHandler interface {
	GetUnreadCounts(context.Context, *connect.Request[v1.GetUnreadCountsRequest]) (*connect.Response[v1.GetUnreadCountsResponse], error)
	MarkDMRead(context.Context, *connect.Request[v1.MarkDMReadRequest]) (*connect.Response[v1.MarkDMReadResponse], error)
	MarkChannelRead(context.Context, *connect.Request[v1.MarkChannelReadRequest]) (*connect.Response[v1.MarkChannelReadResponse], error)
}

// NewNotifyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotifyServiceHandler(svc NotifyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notifyServiceMethods := v1.File_notify_v1_notify_proto.Services().ByName("NotifyService").Methods()
	notifyServiceGetUnreadCountsHandler := connect.NewUnaryHandler(
		NotifyServiceGetUnreadCountsProcedure,
		svc.GetUnreadCounts,
		connect.WithSchema(notifyServiceMethods.ByName("GetUnreadCounts")),
		connect.WithHandlerOptions(opts...),
	)
	notifyServiceMarkDMReadHandler := connect.NewUnaryHandler(
		NotifyServiceMarkDMReadProcedure,
		svc.MarkDMRead,
		connect.WithSchema(notifyServiceMethods.ByName("MarkDMRead")),
		connect.WithHandlerOptions(opts...),
	)
	notifyServiceMarkChannelReadHandler := connect.NewUnaryHandler(
		NotifyServiceMarkChannelReadProcedure,
		svc.MarkChannelRead,
		connect.WithSchema(notifyServiceMethods.ByName("MarkChannelRead")),
		connect.WithHandlerOptions(opts...),
	)
	return "/notify.v1.NotifyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotifyServiceGetUnreadCountsProcedure:
			notifyServiceGetUnreadCountsHandler.ServeHTTP(w, r)
		case NotifyServiceMarkDMReadProcedure:
			notifyServiceMarkDMReadHandler.ServeHTTP(w, r)
		case NotifyServiceMarkChannelReadProcedure:
			notifyServiceMarkChannelReadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotifyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotifyServiceHandler struct{}

func (UnimplementedNotifyServiceHandler) GetUnreadCounts(context.Context, *connect.Request[v1.GetUnreadCountsRequest]) (*connect.Response[v1.GetUnreadCountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notify.v1.NotifyService.GetUnreadCounts is not implemented"))
}

func (UnimplementedNotifyServiceHandler) MarkDMRead(context.Context, *connect.Request[v1.MarkDMReadRequest]) (*connect.Response[v1.MarkDMReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notify.v1.NotifyService.MarkDMRead is not implemented"))
}

func (UnimplementedNotifyServiceHandler) MarkChannelRead(context.Context, *connect.Request[v1.MarkChannelReadRequest]) (*connect.Response[v1.MarkChannelReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notify.v1.NotifyService.MarkChannelRead is not implemented"))
}
