// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/v1/user.proto

package userv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/constell/constell/backend/pkg/proto/user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/user.v1.UserService/GetUser"
	// UserServiceUpdateProfileProcedure is the fully-qualified name of the UserService's UpdateProfile
	// RPC.
	UserServiceUpdateProfileProcedure = "/user.v1.UserService/UpdateProfile"
	// UserServiceListFriendsProcedure is the fully-qualified name of the UserService's ListFriends RPC.
	UserServiceListFriendsProcedure = "/user.v1.UserService/ListFriends"
	// UserServiceSendDMProcedure is the fully-qualified name of the UserService's SendDM RPC.
	UserServiceSendDMProcedure = "/user.v1.UserService/SendDM"
	// UserServiceGetDMHistoryProcedure is the fully-qualified name of the UserService's GetDMHistory
	// RPC.
	UserServiceGetDMHistoryProcedure = "/user.v1.UserService/GetDMHistory"
	// UserServiceGetDMConversationsProcedure is the fully-qualified name of the UserService's
	// GetDMConversations RPC.
	UserServiceGetDMConversationsProcedure = "/user.v1.UserService/GetDMConversations"
)

// UserServiceClient is a client for the user.v1.UserService service.
type UserServiceClient interface {
	// GetUser returns a user's profile.
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	// UpdateProfile modifies the current user's profile.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// ListFriends returns the current user's friend list.
	ListFriends(context.Context, *connect.Request[v1.ListFriendsRequest]) (*connect.Response[v1.ListFriendsResponse], error)
	// SendDM sends a direct message to another user.
	SendDM(context.Context, *connect.Request[v1.SendDMRequest]) (*connect.Response[v1.SendDMResponse], error)
	// GetDMHistory retrieves DM history with a specific user.
	GetDMHistory(context.Context, *connect.Request[v1.GetDMHistoryRequest]) (*connect.Response[v1.GetDMHistoryResponse], error)
	// GetDMConversations lists the user's DM conversations.
	GetDMConversations(context.Context, *connect.Request[v1.GetDMConversationsRequest]) (*connect.Response[v1.GetDMConversationsResponse], error)
}

// NewUserServiceClient constructs a client for the user.v1.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_user_v1_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		getUser: connect.NewClient[v1.GetUserRequest, v1.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.UpdateProfileResponse](
			httpClient,
			baseURL+UserServiceUpdateProfileProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
		listFriends: connect.NewClient[v1.ListFriendsRequest, v1.ListFriendsResponse](
			httpClient,
			baseURL+UserServiceListFriendsProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListFriends")),
			connect.WithClientOptions(opts...),
		),
		sendDM: connect.NewClient[v1.SendDMRequest, v1.SendDMResponse](
			httpClient,
			baseURL+UserServiceSendDMProcedure,
			connect.WithSchema(userServiceMethods.ByName("SendDM")),
			connect.WithClientOptions(opts...),
		),
		getDMHistory: connect.NewClient[v1.GetDMHistoryRequest, v1.GetDMHistoryResponse](
			httpClient,
			baseURL+UserServiceGetDMHistoryProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetDMHistory")),
			connect.WithClientOptions(opts...),
		),
		getDMConversations: connect.NewClient[v1.GetDMConversationsRequest, v1.GetDMConversationsResponse](
			httpClient,
			baseURL+UserServiceGetDMConversationsProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetDMConversations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getUser            *connect.Client[v1.GetUserRequest, v1.GetUserResponse]
	updateProfile      *connect.Client[v1.UpdateProfileRequest, v1.UpdateProfileResponse]
	listFriends        *connect.Client[v1.ListFriendsRequest, v1.ListFriendsResponse]
	sendDM             *connect.Client[v1.SendDMRequest, v1.SendDMResponse]
	getDMHistory       *connect.Client[v1.GetDMHistoryRequest, v1.GetDMHistoryResponse]
	getDMConversations *connect.Client[v1.GetDMConversationsRequest, v1.GetDMConversationsResponse]
}

// GetUser calls user.v1.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// UpdateProfile calls user.v1.UserService.UpdateProfile.
func (c *userServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// ListFriends calls user.v1.UserService.ListFriends.
func (c *userServiceClient) ListFriends(ctx context.Context, req *connect.Request[v1.ListFriendsRequest]) (*connect.Response[v1.ListFriendsResponse], error) {
	return c.listFriends.CallUnary(ctx, req)
}

// SendDM calls user.v1.UserService.SendDM.
func (c *userServiceClient) SendDM(ctx context.Context, req *connect.Request[v1.SendDMRequest]) (*connect.Response[v1.SendDMResponse], error) {
	return c.sendDM.CallUnary(ctx, req)
}

// GetDMHistory calls user.v1.UserService.GetDMHistory.
func (c *userServiceClient) GetDMHistory(ctx context.Context, req *connect.Request[v1.GetDMHistoryRequest]) (*connect.Response[v1.GetDMHistoryResponse], error) {
	return c.getDMHistory.CallUnary(ctx, req)
}

// GetDMConversations calls user.v1.UserService.GetDMConversations.
func (c *userServiceClient) GetDMConversations(ctx context.Context, req *connect.Request[v1.GetDMConversationsRequest]) (*connect.Response[v1.GetDMConversationsResponse], error) {
	return c.getDMConversations.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the user.v1.UserService service.
type UserServiceHandler interface {
	// GetUser returns a user's profile.
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error)
	// UpdateProfile modifies the current user's profile.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// ListFriends returns the current user's friend list.
	ListFriends(context.Context, *connect.Request[v1.ListFriendsRequest]) (*connect.Response[v1.ListFriendsResponse], error)
	// SendDM sends a direct message to another user.
	SendDM(context.Context, *connect.Request[v1.SendDMRequest]) (*connect.Response[v1.SendDMResponse], error)
	// GetDMHistory retrieves DM history with a specific user.
	GetDMHistory(context.Context, *connect.Request[v1.GetDMHistoryRequest]) (*connect.Response[v1.GetDMHistoryResponse], error)
	// GetDMConversations lists the user's DM conversations.
	GetDMConversations(context.Context, *connect.Request[v1.GetDMConversationsRequest]) (*connect.Response[v1.GetDMConversationsResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_user_v1_user_proto.Services().ByName("UserService").Methods()
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateProfileHandler := connect.NewUnaryHandler(
		UserServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(userServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListFriendsHandler := connect.NewUnaryHandler(
		UserServiceListFriendsProcedure,
		svc.ListFriends,
		connect.WithSchema(userServiceMethods.ByName("ListFriends")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceSendDMHandler := connect.NewUnaryHandler(
		UserServiceSendDMProcedure,
		svc.SendDM,
		connect.WithSchema(userServiceMethods.ByName("SendDM")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetDMHistoryHandler := connect.NewUnaryHandler(
		UserServiceGetDMHistoryProcedure,
		svc.GetDMHistory,
		connect.WithSchema(userServiceMethods.ByName("GetDMHistory")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetDMConversationsHandler := connect.NewUnaryHandler(
		UserServiceGetDMConversationsProcedure,
		svc.GetDMConversations,
		connect.WithSchema(userServiceMethods.ByName("GetDMConversations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateProfileProcedure:
			userServiceUpdateProfileHandler.ServeHTTP(w, r)
		case UserServiceListFriendsProcedure:
			userServiceListFriendsHandler.ServeHTTP(w, r)
		case UserServiceSendDMProcedure:
			userServiceSendDMHandler.ServeHTTP(w, r)
		case UserServiceGetDMHistoryProcedure:
			userServiceGetDMHistoryHandler.ServeHTTP(w, r)
		case UserServiceGetDMConversationsProcedure:
			userServiceGetDMConversationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.UpdateProfile is not implemented"))
}

func (UnimplementedUserServiceHandler) ListFriends(context.Context, *connect.Request[v1.ListFriendsRequest]) (*connect.Response[v1.ListFriendsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.ListFriends is not implemented"))
}

func (UnimplementedUserServiceHandler) SendDM(context.Context, *connect.Request[v1.SendDMRequest]) (*connect.Response[v1.SendDMResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.SendDM is not implemented"))
}

func (UnimplementedUserServiceHandler) GetDMHistory(context.Context, *connect.Request[v1.GetDMHistoryRequest]) (*connect.Response[v1.GetDMHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.GetDMHistory is not implemented"))
}

func (UnimplementedUserServiceHandler) GetDMConversations(context.Context, *connect.Request[v1.GetDMConversationsRequest]) (*connect.Response[v1.GetDMConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.UserService.GetDMConversations is not implemented"))
}
