// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchType int32

const (
	SearchType_SEARCH_TYPE_UNSPECIFIED SearchType = 0
	SearchType_SEARCH_TYPE_USERS       SearchType = 1
	SearchType_SEARCH_TYPE_MESSAGES    SearchType = 2
	SearchType_SEARCH_TYPE_DM_MESSAGES SearchType = 3
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "SEARCH_TYPE_UNSPECIFIED",
		1: "SEARCH_TYPE_USERS",
		2: "SEARCH_TYPE_MESSAGES",
		3: "SEARCH_TYPE_DM_MESSAGES",
	}
	SearchType_value = map[string]int32{
		"SEARCH_TYPE_UNSPECIFIED": 0,
		"SEARCH_TYPE_USERS":       1,
		"SEARCH_TYPE_MESSAGES":    2,
		"SEARCH_TYPE_DM_MESSAGES": 3,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_v1_search_proto_enumTypes[0].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_search_v1_search_proto_enumTypes[0]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Types         []SearchType           `protobuf:"varint,2,rep,packed,name=types,proto3,enum=search.v1.SearchType" json:"types,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTypes() []SearchType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResult          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Messages      []*MessageResult       `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	DmMessages    []*DMMessageResult     `protobuf:"bytes,3,rep,name=dm_messages,json=dmMessages,proto3" json:"dm_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetUsers() []*UserResult {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchResponse) GetMessages() []*MessageResult {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchResponse) GetDmMessages() []*DMMessageResult {
	if x != nil {
		return x.DmMessages
	}
	return nil
}

type UserResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Relevance     float64                `protobuf:"fixed64,4,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResult) Reset() {
	*x = UserResult{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResult) ProtoMessage() {}

func (x *UserResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResult.ProtoReflect.Descriptor instead.
func (*UserResult) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *UserResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResult) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserResult) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserResult) GetRelevance() float64 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

type MessageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Relevance     float64                `protobuf:"fixed64,7,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResult) Reset() {
	*x = MessageResult{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResult) ProtoMessage() {}

func (x *MessageResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResult.ProtoReflect.Descriptor instead.
func (*MessageResult) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *MessageResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageResult) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MessageResult) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MessageResult) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *MessageResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResult) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MessageResult) GetRelevance() float64 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

type DMMessageResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	PeerId         string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Relevance      float64                `protobuf:"fixed64,6,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DMMessageResult) Reset() {
	*x = DMMessageResult{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMMessageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMMessageResult) ProtoMessage() {}

func (x *DMMessageResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMMessageResult.ProtoReflect.Descriptor instead.
func (*DMMessageResult) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *DMMessageResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DMMessageResult) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *DMMessageResult) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DMMessageResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DMMessageResult) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DMMessageResult) GetRelevance() float64 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\"h\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12+\n" +
	"\x05types\x18\x02 \x03(\x0e2\x15.search.v1.SearchTypeR\x05types\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb0\x01\n" +
	"\x0eSearchResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.search.v1.UserResultR\x05users\x124\n" +
	"\bmessages\x18\x02 \x03(\v2\x18.search.v1.MessageResultR\bmessages\x12;\n" +
	"\vdm_messages\x18\x03 \x03(\v2\x1a.search.v1.DMMessageResultR\n" +
	"dmMessages\"u\n" +
	"\n" +
	"UserResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\trelevance\x18\x04 \x01(\x01R\trelevance\"\xcf\x01\n" +
	"\rMessageResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\trelevance\x18\a \x01(\x01R\trelevance\"\xba\x01\n" +
	"\x0fDMMessageResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\trelevance\x18\x06 \x01(\x01R\trelevance*w\n" +
	"\n" +
	"SearchType\x12\x1b\n" +
	"\x17SEARCH_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SEARCH_TYPE_USERS\x10\x01\x12\x18\n" +
	"\x14SEARCH_TYPE_MESSAGES\x10\x02\x12\x1b\n" +
	"\x17SEARCH_TYPE_DM_MESSAGES\x10\x032N\n" +
	"\rSearchService\x12=\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponseB\xa4\x01\n" +
	"\rcom.search.v1B\vSearchProtoP\x01ZAgithub.com/constell/constell/backend/pkg/proto/search/v1;searchv1\xa2\x02\x03SXX\xaa\x02\tSearch.V1\xca\x02\tSearch\\V1\xe2\x02\x15Search\\V1\\GPBMetadata\xea\x02\n" +
	"Search::V1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_search_v1_search_proto_goTypes = []any{
	(SearchType)(0),         // 0: search.v1.SearchType
	(*SearchRequest)(nil),   // 1: search.v1.SearchRequest
	(*SearchResponse)(nil),  // 2: search.v1.SearchResponse
	(*UserResult)(nil),      // 3: search.v1.UserResult
	(*MessageResult)(nil),   // 4: search.v1.MessageResult
	(*DMMessageResult)(nil), // 5: search.v1.DMMessageResult
}
var file_search_v1_search_proto_depIdxs = []int32{
	0, // 0: search.v1.SearchRequest.types:type_name -> search.v1.SearchType
	3, // 1: search.v1.SearchResponse.users:type_name -> search.v1.UserResult
	4, // 2: search.v1.SearchResponse.messages:type_name -> search.v1.MessageResult
	5, // 3: search.v1.SearchResponse.dm_messages:type_name -> search.v1.DMMessageResult
	1, // 4: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	2, // 5: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		EnumInfos:         file_search_v1_search_proto_enumTypes,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
